'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Windows.Forms

Namespace My
    
    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    'or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click "My Project" in the Solution Explorer)
    ' and make changes in the "Application" tab.
    '
    Partial Friend Class MyApplication
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined)
            IsSingleInstance = false
            EnableVisualStyles = true
            SaveMySettingsOnExit = true
            ShutDownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
        End Sub
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = Global.IncomeTaxEvaluationSystem.Forms.LoginForm
        End Sub
    End Class
End Namespace
