services:
  - type: web
    name: project6-rag-rest-api
    runtime: python
    rootDir: 24.LangChain2/Project6/RAG-REST-API
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
