import MarkdownMessage from "./MarkdownMessage";
import { DownloadIcon, XIcon } from "./icons";

export interface PrintBlock {
  question?: string; // shown as a "Q:" heading (conversation export)
  markdown: string;
}

export default function PrintPreviewModal({
  title,
  blocks,
  loading,
  onClose,
}: {
  title: string;
  blocks: PrintBlock[];
  loading?: boolean;
  onClose: () => void;
}) {
  const print = () => {
    document.body.classList.add("printing");
    const cleanup = () => {
      document.body.classList.remove("printing");
      window.removeEventListener("afterprint", cleanup);
    };
    window.addEventListener("afterprint", cleanup);
    setTimeout(() => {
      window.print();
      setTimeout(cleanup, 500);
    }, 50);
  };

  return (
    <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4 backdrop-blur-sm">
      <div className="flex max-h-[88vh] w-full max-w-2xl flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl dark:border-white/10 dark:bg-slate-900">
        <div className="no-print flex items-center justify-between border-b border-slate-200 px-5 py-3 dark:border-white/10">
          <h2 className="text-base font-bold">{title}</h2>
          <div className="flex items-center gap-2">
            <button
              onClick={print}
              disabled={loading || blocks.length === 0}
              className="inline-flex items-center gap-1.5 rounded-lg bg-gradient-to-br from-brand-500 to-accent-500 px-3 py-1.5 text-sm font-semibold text-white transition hover:opacity-90 disabled:opacity-50"
            >
              <DownloadIcon width={15} height={15} /> Print / Save PDF
            </button>
            <button onClick={onClose} className="grid h-8 w-8 place-items-center rounded-lg text-slate-500 hover:bg-slate-100 dark:hover:bg-white/10">
              <XIcon width={18} height={18} />
            </button>
          </div>
        </div>

        <div className="print-only overflow-y-auto px-6 py-5">
          <h1 className="mb-4 text-xl font-extrabold text-slate-900 dark:text-white">
            {title}
          </h1>
          {loading ? (
            <p className="py-10 text-center text-slate-400">Building…</p>
          ) : (
            blocks.map((b, i) => (
              <div key={i} className="mb-4">
                {b.question && <p className="print-q mb-1 font-semibold text-brand-700 dark:text-brand-300">Q: {b.question}</p>}
                <MarkdownMessage content={b.markdown} />
              </div>
            ))
          )}
          <p className="mt-6 border-t border-slate-200 pt-2 text-[11px] text-slate-400 dark:border-white/10">
            Generated by GateOverflow Chatbot · gateoverflow.in
          </p>
        </div>
      </div>
    </div>
  );
}
