'------------------------------------------------------------------------------
' <auto-generated>
'     Declares the runat="server" controls for the matching page/master.
'     Regenerated by Visual Studio when the markup changes.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace ITEMS

    Partial Public Class ClientEditPage

        '''<summary>litMode control.</summary>
        Protected WithEvents litMode As Global.System.Web.UI.WebControls.Literal

        '''<summary>litTitle control.</summary>
        Protected WithEvents litTitle As Global.System.Web.UI.WebControls.Literal

        '''<summary>txtPan control.</summary>
        Protected WithEvents txtPan As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtName control.</summary>
        Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtFather control.</summary>
        Protected WithEvents txtFather As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtDob control.</summary>
        Protected WithEvents txtDob As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtAddr control.</summary>
        Protected WithEvents txtAddr As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtPin control.</summary>
        Protected WithEvents txtPin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtTel control.</summary>
        Protected WithEvents txtTel As Global.System.Web.UI.WebControls.TextBox

        '''<summary>ddlCat control.</summary>
        Protected WithEvents ddlCat As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>ddlRes control.</summary>
        Protected WithEvents ddlRes As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>ddlSex control.</summary>
        Protected WithEvents ddlSex As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>txtWard control.</summary>
        Protected WithEvents txtWard As Global.System.Web.UI.WebControls.TextBox

        '''<summary>litErr control.</summary>
        Protected WithEvents litErr As Global.System.Web.UI.WebControls.Literal

        '''<summary>btnSave control.</summary>
        Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    End Class

End Namespace
