'------------------------------------------------------------------------------
' <auto-generated>
'     Declares the runat="server" controls for the matching page/master.
'     Regenerated by Visual Studio when the markup changes.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace ITEMS

    Partial Public Class FirmAccountPage

        '''<summary>litCrumb control.</summary>
        Protected WithEvents litCrumb As Global.System.Web.UI.WebControls.Literal

        '''<summary>litTitle control.</summary>
        Protected WithEvents litTitle As Global.System.Web.UI.WebControls.Literal

        '''<summary>btnNew control.</summary>
        Protected WithEvents btnNew As Global.System.Web.UI.WebControls.Button

        '''<summary>pnlList control.</summary>
        Protected WithEvents pnlList As Global.System.Web.UI.WebControls.Panel

        '''<summary>gv control.</summary>
        Protected WithEvents gv As Global.System.Web.UI.WebControls.GridView

        '''<summary>pnlForm control.</summary>
        Protected WithEvents pnlForm As Global.System.Web.UI.WebControls.Panel

        '''<summary>ddlFirm control.</summary>
        Protected WithEvents ddlFirm As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>txtA1 control.</summary>
        Protected WithEvents txtA1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtA2 control.</summary>
        Protected WithEvents txtA2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>litLeftHead control.</summary>
        Protected WithEvents litLeftHead As Global.System.Web.UI.WebControls.Literal

        '''<summary>phLeft control.</summary>
        Protected WithEvents phLeft As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>litRightHead control.</summary>
        Protected WithEvents litRightHead As Global.System.Web.UI.WebControls.Literal

        '''<summary>phRight control.</summary>
        Protected WithEvents phRight As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>btnSave control.</summary>
        Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

        '''<summary>btnCancel control.</summary>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

    End Class

End Namespace
