'------------------------------------------------------------------------------
' <auto-generated>
'     Declares the runat="server" controls for the matching page/master.
'     Regenerated by Visual Studio when the markup changes.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace ITEMS

    Partial Public Class LoginPage

        '''<summary>txtUser control.</summary>
        Protected WithEvents txtUser As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtPass control.</summary>
        Protected WithEvents txtPass As Global.System.Web.UI.WebControls.TextBox

        '''<summary>litErr control.</summary>
        Protected WithEvents litErr As Global.System.Web.UI.WebControls.Literal

        '''<summary>btnLogin control.</summary>
        Protected WithEvents btnLogin As Global.System.Web.UI.WebControls.Button

    End Class

End Namespace
