'------------------------------------------------------------------------------
' <auto-generated>
'     Declares the runat="server" controls for the matching page/master.
'     Regenerated by Visual Studio when the markup changes.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace ITEMS

    Partial Public Class ReturnEditPage

        '''<summary>litTitle control.</summary>
        Protected WithEvents litTitle As Global.System.Web.UI.WebControls.Literal

        '''<summary>ddlClient control.</summary>
        Protected WithEvents ddlClient As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>ddlType control.</summary>
        Protected WithEvents ddlType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>txtAy1 control.</summary>
        Protected WithEvents txtAy1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtAy2 control.</summary>
        Protected WithEvents txtAy2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtSalary control.</summary>
        Protected WithEvents txtSalary As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtHouse control.</summary>
        Protected WithEvents txtHouse As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtBusiness control.</summary>
        Protected WithEvents txtBusiness As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtStcg control.</summary>
        Protected WithEvents txtStcg As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtLtcg control.</summary>
        Protected WithEvents txtLtcg As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtOther control.</summary>
        Protected WithEvents txtOther As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtClub control.</summary>
        Protected WithEvents txtClub As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtVia control.</summary>
        Protected WithEvents txtVia As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtTds control.</summary>
        Protected WithEvents txtTds As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtAdvance control.</summary>
        Protected WithEvents txtAdvance As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtSelf control.</summary>
        Protected WithEvents txtSelf As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtInterest control.</summary>
        Protected WithEvents txtInterest As Global.System.Web.UI.WebControls.TextBox

        '''<summary>txtRelief control.</summary>
        Protected WithEvents txtRelief As Global.System.Web.UI.WebControls.TextBox

        '''<summary>litErr control.</summary>
        Protected WithEvents litErr As Global.System.Web.UI.WebControls.Literal

        '''<summary>btnCompute control.</summary>
        Protected WithEvents btnCompute As Global.System.Web.UI.WebControls.Button

        '''<summary>btnSave control.</summary>
        Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

        '''<summary>litRegime control.</summary>
        Protected WithEvents litRegime As Global.System.Web.UI.WebControls.Literal

        '''<summary>litComp control.</summary>
        Protected WithEvents litComp As Global.System.Web.UI.WebControls.Literal

    End Class

End Namespace
