'------------------------------------------------------------------------------
' <auto-generated>
'     Declares the runat="server" controls for the matching page/master.
'     Regenerated by Visual Studio when the markup changes.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace ITEMS

    Partial Public Class SiteMaster

        '''<summary>Head control.</summary>
        Protected WithEvents Head As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>Crumb control.</summary>
        Protected WithEvents Crumb As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>litInitial control.</summary>
        Protected WithEvents litInitial As Global.System.Web.UI.WebControls.Literal

        '''<summary>litUser control.</summary>
        Protected WithEvents litUser As Global.System.Web.UI.WebControls.Literal

        '''<summary>btnLogout control.</summary>
        Protected WithEvents btnLogout As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>Main control.</summary>
        Protected WithEvents Main As Global.System.Web.UI.WebControls.ContentPlaceHolder

    End Class

End Namespace
